### ISSUE TITLE
next prev still working?

### ISSUE THREAD

**Issue by merijnponzo** [tannerhodges/snap-slider#25]
Hello, great plugin!

Question, should
```
data-snap-slider-prev="<SELECTOR>"
```
go into data-snap-slider-nav ?
Maybe this could more clearly in the documentation

Otherwise, it's not working
But 
```
 :data-snap-slider-goto="`${data.__typename}:prev`"
```
is working

**Comment by tannerhodges** [comment]
Hey @merijnponzo, can you share a code example or URL where you're seeing `data-snap-slider-prev` not working?

Here's a CodePen showing how it works on both the Nav and Container elements: https://codepen.io/tannerhodges/pen/MWOPjXp

At the risk of over-explaining, here's a rundown of what it sounds like _might_ be happening, some ways you can fix it, and some ideas for how we might improve this feature…

Would love to know your thoughts.

## What's happening? Probably a race condition.

🤔 It sounds like, assuming you're using Vue or another JS framework, you may be running into a race condition where Snap Slider initializes _before_ the `data-snap-slider-prev` attribute is bound to the element.

If that's the case, you may need to either use the JS API to manually initialize your sliders, or, if you're already doing that, then wait an extra tick before calling `new SnapSlider()`.

That way your options are set before the slider initializes and not after.

## How does `data-snap-slider-prev` work?

Currently, Snap Slider v2 only checks for Container and Nav options like `data-snap-slider-prev` during its `init()` method ([see here](https://github.com/tannerhodges/snap-slider/blob/0d214a07f0a4f48fdd532a4b8476308d513b38e8/src/snap-slider.js#L137)).

`init()` is only called in one of 2 places: Snap Slider's `constructor()` and its `reset()` method.

So there are 3 moments when Snap Slider actually checks for your Container and Nav options:

1. On `DOMContentLoaded` when Snap Slider auto-initializes all `data-snap-slider` elements.
2. When you call `new SnapSlider()` to create new slider instances.
3. When you call `.reset()` on a specific slider instance.

By default, if you don't make any calls to `new SnapSlider()` or `.reset()`, the only time `data-snap-slider-prev` is checked is during the initial page load on `DOMContentLoaded`:

https://github.com/tannerhodges/snap-slider/blob/0d214a07f0a4f48fdd532a4b8476308d513b38e8/src/snap-slider.js#L1640-L1651

This means that if you bind attributes later in the page load then the only ways to make sure those options take effect are to either:

- Use `new SnapSlider()` instead of the `data-snap-slider` attribute, or…
- Call `.reset()` on your specific slider instance (e.g., `document.querySelector('.your-slider').SnapSlider.reset()`).

## Why does `data-snap-slider-goto` still work?

Goto button events are delegated. Instead of binding event listeners to each individual button element, Snap Slider handles all goto buttons with a single event listener on the `body`.

That means that any element with a `data-snap-slider-goto` attribute will automatically be handled by Snap Slider's "global" click event listener, no matter when it's added to the DOM.

😕 However, Snap Slider does not delegate events for _custom selectors_.

`data-snap-slider-prev` is basically a hint telling the Snap Slider constructor to add `data-snap-slider-goto="prev"` to any buttons with a matching selector inside your slider's Container or Nav elements.

So unless you set `data-snap-slider-prev` before it initializes, Snap Slider will miss that option and fail to add `data-snap-slider-goto="prev"` to your previous buttons.

## How can we make this better?

At the least, we can definitely update the docs to better explain how goto buttons work, specifically how the `data-snap-slider-prev` attribute works and how/when to use it.

We should also probably document clear examples for using Snap Slider with JS frameworks, outlining the potential race conditions, and how to properly mount/unmount slider components.

We _could_ also revisit how goto buttons work and try to drive out a more intuitive, easy-to-use implementation… That would probably require breaking changes, but it could be something worth considering in v3 #20.

❓ Thoughts? Do you think documentation would be enough here, or should we consider going further?

Hopefully this helps some in the meantime.

**Comment by merijnponzo** [comment]
Hi Tanner,
Thanks for extensive tips & tricks.

My guess is that it wasn't working because i didn't add:
**data-snap-slider-nav** as a wrapper around my prev and next buttons


So for nuxt, adding the snap slider module to your your page scripts works, you can even defer it so it's loaded as last

nuxt.config.js:
```
head: {
 script: [
      {
        hid: "snap-slider",
        src: "https://cdn.jsdelivr.net/npm/@tannerhodges/snap-slider@2.0.3/snap-slider.min.js",
        body: true,
        defer: true,
      },
    ],
}
```
With a navigation wrapper with  **data-snap-slider-nav="example"** and next and prev buttons with **data-snap-slider-goto="prev"**

The example above would the easiest way, however it does not follow any $route changes.

So for route changes, or more interactive or lazyloaded components within your vue/nuxt framework etc then i should add snap-slider as a plugin (for nuxt)

yarn add @tannerhodges/snap-slider

then add to your nuxt.config.js:
```
 plugins: [
     { src: "~/plugins/snap-slider.js", mode: "client" },
  ],
```

in plugins/snap-slider.js
```
import SnapSlider from "@tannerhodges/snap-slider";
export default (context, inject) => {
  inject("snapslider", SnapSlider);
};
```
and then within your page or component.vue 

```
  mounted() {
    const slider = new SnapSlider(".example", {
      nav: ".example-nav",
    });
  },
```
Make sure it's within mounted since it's client sided.

thanks!

**Comment by tannerhodges** [comment]
Ah, excellent! Glad you were able to get that sorted out.

👌 These docs will be helpful to add in #20 for anyone else using Nuxt.js or similar frameworks. I'll make a todo to add these to the v3 release.

In the meantime, I'll mark this issue as resolved.

🙏 Let me know if there's anything else I can help with.
