### ISSUE TITLE
Disabling 'Peek' slides.

### ISSUE THREAD

**Issue by koendolron** [tannerhodges/snap-slider#28]
Hi Tanner,

I am using your plugin to create some awesome sliders. When using them for a product slider, with 12 products in total and only 4,5 of them in the viewport, clicking on one of the products inside the viewport causes the slider to move to the clicked product, instead of just going to the page as told in the <a> tag.

Removing the dot and arrow navigation had no result. 

Is there some way to disable that when a user clicks a slide the slider actually moves? It should only move by scrolling or using the navigation elements.

Thanks in advance,
Koen

Below is my code with Tailwind and Twig:

<div class="tab-pane relative fade active show" id="ladies-tab-pane" role="tabpanel" aria-labelledby="ladies-tab">
	<div class="product-tab-list w-full flex grid-gap-4 snap-x snap-mandatory scroll-pl-4 overflow-x-auto has-loaded" data-snap-slider="ladies" data-snap-slider-slides="" data-snap-slider-align="" data-snap-slider-start="1" data-snap-slider-loop="false">
		<div class="product-tab-item snap-start shrink-0 w-2/5 first:pl-4 last:pr-4 md:first:pl-0 md:last:pr-0 md:w-1/5 xl:max-w-[240px] is-current" tabindex="-1">
			PRODUCT CARD DATA
		</div>
		<div class="product-tab-item snap-start shrink-0 w-2/5 first:pl-4 last:pr-4 md:first:pl-0 md:last:pr-0 md:w-1/5 xl:max-w-[240px]" tabindex="-1" aria-hidden="true">
			PRODUCT CARD DATA
		</div>
		<div class="product-tab-item snap-start shrink-0 w-2/5 first:pl-4 last:pr-4 md:first:pl-0 md:last:pr-0 md:w-1/5 xl:max-w-[240px]" tabindex="-1" aria-hidden="true">
			PRODUCT CARD DATA
		</div>
		<div class="product-tab-item snap-start shrink-0 w-2/5 first:pl-4 last:pr-4 md:first:pl-0 md:last:pr-0 md:w-1/5 xl:max-w-[240px]" tabindex="-1" aria-hidden="true">
			PRODUCT CARD DATA
		</div>
		<div class="product-tab-item snap-start shrink-0 w-2/5 first:pl-4 last:pr-4 md:first:pl-0 md:last:pr-0 md:w-1/5 xl:max-w-[240px]" tabindex="-1" aria-hidden="true">
			PRODUCT CARD DATA
		</div>
		<div class="product-tab-item snap-start shrink-0 w-2/5 first:pl-4 last:pr-4 md:first:pl-0 md:last:pr-0 md:w-1/5 xl:max-w-[240px]" tabindex="-1" aria-hidden="true">
			PRODUCT CARD DATA
		</div>
		<div class="product-tab-item snap-start shrink-0 w-2/5 first:pl-4 last:pr-4 md:first:pl-0 md:last:pr-0 md:w-1/5 xl:max-w-[240px]" tabindex="-1" aria-hidden="true">
			PRODUCT CARD DATA
		</div>
		<div class="product-tab-item snap-start shrink-0 w-2/5 first:pl-4 last:pr-4 md:first:pl-0 md:last:pr-0 md:w-1/5 xl:max-w-[240px]" tabindex="-1" aria-hidden="true">
			PRODUCT CARD DATA
		</div>
		<div class="product-tab-item snap-start shrink-0 w-2/5 first:pl-4 last:pr-4 md:first:pl-0 md:last:pr-0 md:w-1/5 xl:max-w-[240px]" tabindex="-1" aria-hidden="true">
			PRODUCT CARD DATA
		</div>
		<div class="product-tab-item snap-start shrink-0 w-2/5 first:pl-4 last:pr-4 md:first:pl-0 md:last:pr-0 md:w-1/5 xl:max-w-[240px]" tabindex="-1" aria-hidden="true">
			PRODUCT CARD DATA
		</div>
		<div class="product-tab-item snap-start shrink-0 w-2/5 first:pl-4 last:pr-4 md:first:pl-0 md:last:pr-0 md:w-1/5 xl:max-w-[240px]" tabindex="-1" aria-hidden="true">
			PRODUCT CARD DATA
		</div>
	</div>

	<ul class="snap-slider-nav snap-slider-nav-dots mt-4" data-snap-slider-nav="ladies">
		<li>
			<button type="button" class="snap-slider-nav-button is-current" data-snap-slider-goto="1">1</button>
		</li>
		<li>
			<button type="button" class="snap-slider-nav-button" data-snap-slider-goto="2">2</button>
		</li>
		<li>
			<button type="button" class="snap-slider-nav-button" data-snap-slider-goto="3">3</button>
		</li>
		<li>
			<button type="button" class="snap-slider-nav-button" data-snap-slider-goto="4">4</button>
		</li>
		<li>
			<button type="button" class="snap-slider-nav-button" data-snap-slider-goto="5">5</button>
		</li>
		<li>
			<button type="button" class="snap-slider-nav-button" data-snap-slider-goto="6">6</button>
		</li>
		<li>
			<button type="button" class="snap-slider-nav-button" data-snap-slider-goto="7">7</button>
		</li>
		<li>
			<button type="button" class="snap-slider-nav-button" data-snap-slider-goto="8">8</button>
		</li>
		<li>
			<button type="button" class="snap-slider-nav-button" data-snap-slider-goto="9">9</button>
		</li>
		<li>
			<button type="button" class="snap-slider-nav-button" data-snap-slider-goto="10">10</button>
		</li>
		<li>
			<button type="button" class="snap-slider-nav-button" data-snap-slider-goto="11">11</button>
		</li>
	</ul>

	<ul class="snap-slider-nav snap-slider-nav-arrows mt-4" data-snap-slider-nav="ladies">
		<li>
			<button type="button" data-snap-slider-goto="prev" class="snap-slider-arrow snap-slider-nav-prev is-disabled">
				ARROW
			</button>
		</li>
		<li>
			<button type="button" data-snap-slider-goto="next" class="snap-slider-arrow snap-slider-nav-next">
				ARROW
			</button>
		</li>
	</ul>
</div>

This generates the following section
![Schermafbeelding 2022-03-04 om 14 03 04](https://user-images.githubusercontent.com/81799034/156768733-0e944ebd-9e5e-4880-a79c-118a21a61038.png)

**Comment by tannerhodges** [comment]
🤔 Hm… This sounds similar to https://github.com/tannerhodges/snap-slider/issues/23#issuecomment-962666931.

## The problem: focus handling and inline anchors

💡 I think the root of the problem is a combination of two things:

1. Snap Slider v2's aggressive focus handling.*
2. Links with small target sizes making it easy to focus on a slide without actually following the link.

In general, Snap Slider should not prevent anchors from being followed. However, clicks on any non-anchor elements will focus that slide and scroll it into position.

_*I've realized this aggressive focus handling was a mistake, and have removed that behavior in v3._

## How to fix: either CSS `display: block` or upgrade to v3 alpha

👉 Here's a CodePen example based on your sample markup with a before/after showing how to quickly fix the issue with CSS: https://codepen.io/tannerhodges/pen/OJzmvZW

While there are other ways to work around this issue, I'd recommend either:

1. **Using CSS `display: block` to increase the target size of your anhcors**. This way clicks will be more likely to follow your links instead of triggering Snap Slider's focus handling.
2. **Upgrading to the latest alpha release of Snap Slider v3**. https://codepen.io/tannerhodges/pen/jOYmxdo There are some breaking changes, and I haven't finished preparing #20 for full release, but it may be more helpful in case the CSS changes aren't enough for your situation.

Hopefully this helps highlight the problem and some ways to quickly fix it.

**Comment by tannerhodges** [comment]
Hey @koendolron, checking in here.

❓ Were you able to solve this issue?

**Comment by tannerhodges** [comment]
Hey @koendolron, since I haven't heard back I'm going to go ahead and close this issue.

Feel free to re-open it, though, if you still have questions I can help with.
